# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RWRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "EZAudio", "~> 1.1.4"

end
